apiVersion: tekton.dev/v1beta1
kind: Task
abc11: random
metadata:
  name: sample-out-task
spec:
  inputs:
    params:
      - name: buildnumber
        description: test
  params:
    - name: text
  steps:
    - name: task-two-step-four
      image: ubuntu
      env:
        - name: BUILD_NUMBER
          value: $(inputs.params.buildnumber)
        - name: TEXT_VAL
          value: $(params.text)
      nav: kaushal
      command: ['bash', '-c']
      args:
        - echo 'Retries check:';
          if [ "$(context.task.retry-count)" == "$(context.task.retry-count)" ]; then
          echo "This is the last retry."
          exit 0;
          fi
          echo "The PipelineTask has retried $(context.task.retry-count) times."
          exit 1
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: buildnumber
      description: the pipeline pvc name
    - name: text
  tasks:
    - name: sample-out-task
      retries: 5
      taskRef:
        name: sample-out-task
      params:
        - name: text
          value: $(params.text)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: buildnumber
      description: thebuildnuminput
      default: buildnumberfailedjerh
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: buildnumber
          value: $(params.buildnumber)
        - name: text
          value: $(params.text)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/open-toolchain/hello-tekton"
    - name: revision
      value: "master"
    - name: text
      value: $(params.TEXT)
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
