apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  steps:
    - name: task-one-step-one
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo 'Retries check:';
          if [ "$(context.task.retry-count)" == "$(context.task.retry-count)" ]; then
          echo "This is the last retry."
          exit 0;
          fi
          echo "The PipelineTask has retried $(context.task.retry-count) times."
          exit 1
    - name: task-two
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo "SHAZBOT2"      
